Sync
Update nvim config, update fish config.
Switch from Brave to Firefox Developer Edition

diff --git a/mac/make_links b/mac/make_links
--- a/mac/make_links
+++ b/mac/make_links
@@ -2,31 +2,30 @@
 DIR="$(git rev-parse --show-toplevel)"
 
 linkIfNotExists() {
-  if [ $# -lt 1 ]; then
-    echo "developer error: cannot link without any arguments"
-    exit 1
-  fi
-  LINK_TO="${DIR}/${1}"
-  LINK_FROM="${HOME}/${2:-$1}"
-  if [ -f "${LINK_FROM}" ] || [ -d "${LINK_FROM}" ]; then
-    echo "Won't link ${LINK_FROM} because it already exists."
-    return 1
-  else
-    echo "Linking ${LINK_FROM}"
-    ln -s "${LINK_TO}" "${LINK_FROM}"
-    return 0
-  fi
+	if [ $# -lt 1 ]; then
+		echo "developer error: cannot link without any arguments"
+		exit 1
+	fi
+	LINK_TO="${DIR}/${1}"
+	LINK_FROM="${HOME}/${2:-$1}"
+	if [ -f "${LINK_FROM}" ] || [ -d "${LINK_FROM}" ]; then
+		echo "Won't link ${LINK_FROM} because it already exists."
+		return 1
+	else
+		echo "Linking ${LINK_FROM}"
+		ln -s "${LINK_TO}" "${LINK_FROM}"
+		return 0
+	fi
 }
 
 linkIfNotExists ".config/fish"
 linkIfNotExists ".config/kitty"
 linkIfNotExists ".config/lvim"
 linkIfNotExists ".config/nvim"
-if linkIfNotExists ".config/astronvim"; then 
-  echo "  Linked AstroNvim User config, but it will only be loaded if XDG_CONFIG_HOME is set correctly."
-  echo "  Currently XDG_CONFIG_HOME is set to ${XDG_CONFIG_HOME:-"nothing."}"
+if linkIfNotExists ".config/astronvim"; then
+	echo "  Linked AstroNvim User config, but it will only be loaded if XDG_CONFIG_HOME is set correctly."
+	echo "  Currently XDG_CONFIG_HOME is set to ${XDG_CONFIG_HOME:-"nothing."}"
 fi
-linkIfNotExists ".config/helix"
 linkIfNotExists ".config/ranger"
 linkIfNotExists ".config/sketchybar"
 linkIfNotExists ".config/nap"
