Add shellcheck to newscript script
Remove GME scripts

diff --git a/scripts/newscript b/scripts/newscript
--- a/scripts/newscript
+++ b/scripts/newscript
@@ -3,13 +3,24 @@ if [ "$#" -ne 1 ]; then
   echo "Usage: $0 NEW_SCRIPT_NAME" >&2
   exit 1
 fi
-HOME=`eval echo ~`
+HOME=$(eval echo ~)
 FILEPATH="${HOME}/repos/alexmeuer/dotfiles/scripts/${1}"
+
+do_shellcheck() {
+    if command -v shellcheck >/dev/null 2>&1; then
+      shellcheck "${FILEPATH}"
+      return $?
+    else
+      echo "ShellCheck not found; cannot analyze script. Consider installing via your package manager." >&2
+    fi
+}
+trap do_shellcheck EXIT
+
 if [ -e "${FILEPATH}" ]; then
   echo "${1} already exists" >&2
   nvim "${FILEPATH}"
   exit $?
 fi
 
-touch ${FILEPATH} && echo "#!/bin/sh\npwd\nexit \$?" > ${FILEPATH} && nvim ${FILEPATH} && chmod +x ${FILEPATH}
+touch "${FILEPATH}" && printf "#!/bin/sh\npwd\nexit \$?" > "${FILEPATH}" && nvim "${FILEPATH}" && chmod +x "${FILEPATH}"
 exit $?
